theme: jekyll-theme-dinky

<a href="AGOL_Dependency_Automator_GitHub.md" target="_blank" style="display:inline-block; padding:10px 20px; background-color:#4CAF50; color:white; text-decoration:none; border-radius:5px;">
    Open Notebook
</a>
